kind: Deployment
apiVersion: apps/v1
metadata:
  name: django-depl
  namespace: notes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      initContainers:
        - name: run-migrations
          image: soniya06/django-notes-app:v1
          command: ['sh', '-c', 'python manage.py migrate --noinput']
          env:
            - name: DB_NAME
              value: "notes"
            - name: DB_USER
              value: "cat"
            - name: DB_PASSWORD
              value: "meow"
            - name: DB_HOST
              value: "mysql-svc"
            - name: DB_PORT
              value: "3306"
            - name: SECRET_KEY
              value: "django-insecure-my-super-secret-key-for-notes-app-2025"
      containers:
        - name: django-cont
          image: soniya06/django-notes-app:v1
          command: ['sh', '-c', 'python manage.py collectstatic --noinput && gunicorn notesapp.wsgi --bind 0.0.0.0:8000']
          ports:
            - containerPort: 8000
          env:
            - name: DB_NAME
              value: "notes"
            - name: DB_USER
              value: "cat"
            - name: DB_PASSWORD
              value: "meow"
            - name: DB_HOST
              value: "mysql-svc"
            - name: DB_PORT
              value: "3306"
            - name: SECRET_KEY
              value: "django-insecure-my-super-secret-key-for-notes-app-2025"
            - name: DEBUG
              value: "True"
            - name: ALLOWED_HOSTS
              value: "*"
          livenessProbe:
            httpGet:
              path: /admin
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /admin
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
---
kind: Service
apiVersion: v1
metadata:
  name: django-svc
  namespace: notes-app
spec:
  type: NodePort
  selector:
    app: django
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30007
