kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-depl
  namespace: notes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-cont
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-svc
  namespace: notes-app
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: notes-app
data:
  default.conf: |
    server {
      listen 80;
      server_name localhost;

      location /static/ {
        proxy_pass http://django-svc:8000/static/;
      }

      location / {
        proxy_pass http://django-svc:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
    }
